#pragma once

#include <cstdint>
#include <string>

namespace QTrading::Execution {

/// @brief Order side for execution.
enum class OrderAction {
    Buy,
    Sell
};

/// @brief Order type for execution.
enum class OrderType {
    Market,
    Limit
};

/// @brief Execution urgency hint.
enum class OrderUrgency {
    Low,
    Medium,
    High
};

/// @brief Concrete order request generated by execution engine.
struct ExecutionOrder {
    /// @brief Milliseconds since epoch.
    std::uint64_t ts_ms = 0;
    /// @brief Trading symbol.
    std::string symbol;
    /// @brief Buy or Sell action.
    OrderAction action = OrderAction::Buy;
    /// @brief Quantity to trade.
    double qty = 0.0;
    /// @brief Limit price when OrderType::Limit.
    double price = 0.0;
    /// @brief Market or Limit.
    OrderType type = OrderType::Market;
    /// @brief Whether order must reduce existing exposure.
    bool reduce_only = false;
    /// @brief Urgency hint for execution.
    OrderUrgency urgency = OrderUrgency::Low;
};

} // namespace QTrading::Execution
